# Generated by Django 2.2.13 on 2021-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sci1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.CharField(max_length=200, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Reference', models.CharField(max_length=200, null=True)),
                ('ref', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
